nicknames={"satan":"David Bausola", 
               "stan":"David Bausola",
               "lobsterGod":"David Bausola", 
               "marcusjhbrownv2":"David Bausola",
               "cunt":"David Bausola",
               "oil":"Adam Hoyle",
               "atom":"Adam Hoyle",
               "ham":"Adam Hoyle",
               "bashy":"Ben Bashford",
               "splashford":"Ben Bashford",
               "hank":"Henry Cooke",
               "cookie":"Henry Cooke",
               "warren":"Lauren Brown",
               "wazza":"Lauren Brown",
               "mario":"Maria Aretoulaki",
               "greek":"Maria Aretoulaki",
               "mjays":"Martin Spindler",
               "spider":"Martin Spindler",
               "ferbs":"Sarah Ferber",
               "donkey":"Sarah Ferber",
               "eric":"shardcore",
               "shard":"shardcore",
               "shardy":"shardcore",
               "kaiser":"The Kaiser",
               "dovehand":"The Kaiser",
               "anus":"The Kaiser",
               "tony":"Toby Barnes",
               "adman":"Toby Barnes",
               "tone":"Toby Barnes",
               "gary":"Gregory Povey",
               "conch":"Gregory Povey",
               "greggie":"Gregory Povey",
               "gazza":"Gregory Povey",
               "divvy":"Gregory Povey",
               "garry":"Gregory Povey",
               "doris":"Louisa Heinrich",
               "dozza":"Louisa Heinrich"}
